### PR TITLE
Bug Fix: Travis CI Fix - Update .travis.yml

### LINKED ISSUE #136: Bug: Travis CI Build-Unknown error
#### This issue is about [bug/enhancement] 

- [x] This Bug Fix/Enhancement is worth adding to this repository.
- [x] Issue Title is in form `Bug/Enhancement: Name`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Actual Behaviour**
The Travis CI is not enabled on this repo. Mentors should enable it by going on dashboard of `travis-ci.org`

**Expected Behaviour**
If linked successfully, travis should then build the android app and update the build status.

**Steps to reproduce it**
Just simply disable travis-ci on this repo.

**Screenshots of the issue**
screen shot 2018-11-16 at 9 35 10 pm

**Would you like to work on the issue?**
Yes

**System Specifications**
  - Version: -
  - Platform: -
  - Subsystem: -

### PR DESCRIPTION
**Pull request by sidhyatikku**
#### Travis CI `.travis.yml` fix

- This Pull request
   - [x] Fixes a bug.
   - [ ] Implements a new feature.
- [x] I have read the **[CONTRIBUTING.md]** .
- [x] I have included a description of changes below.
- [ ] I have included screenshots  showing before and after the changes were made.
- [x] I have squashed the commits **(mandatory)**.

## Description / Changes

- Fixes #136 
In the previous `.travis.yml` build-tools version was `28.0.0` whereas app build-tools version in `app/build.gradle` is `28.0.3`. I hope this would fix the issue.

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@aashutoshrathi Will this fix `.travis.yml` ? #136

**Comment by sidhyatikku** [comment]
@aashutoshrathi they had redundant spaces so I deleted some of that. Main change was in line 9

**Comment by aashutoshrathi** [comment]
@the-dagger This looks ready to merge to me.
Since this is not a task.
I think this should be merged ASAP.

**Comment by sidhyatikku** [comment]
@aashutoshrathi You're welcome! 🎉

**Pull request merged**
