### PR TITLE
Added Custom pin and fixed capital package name bugs.

### PR DESCRIPTION
**Pull request by crowded-geek**
Check by changing each `[ ]` to `[x]` Please take note of the white-space as it matters.

- This Pull request
   - [x] Fixes a bug.
   - [x] Implements a new feature.
- [x] I have read the **[CONTRIBUTING.md]** .
- [x] I have included a description of changes below.
- [x] I have included screenshots  showing before and after the changes were made.
- [x] I have squashed the commits **(mandatory)**.

## Description / Changes

- Fixes [#81](https://github.com/JBossOutreach/visiting-card-android/issues/81)
- Link to [task](https://codein.withgoogle.com/dashboard/task-instances/5407780040081408/) 

## Screenshots

screenshot_20181101-195000

### CODE REVIEW

**Comment by Priya997** [comment]
@the-dagger we can merge this LGTM 👍

**Comment by the-dagger** [comment]
Sounds good, @crowded-geek Can you please resolve the conflicts? :)

**Comment by crowded-geek** [comment]
@the-dagger Sure

**Comment by crowded-geek** [comment]
@the-dagger This PR couldn't be edited as I had deleted the old fork but here's the [PR](https://github.com/JBossOutreach/visiting-card-android/pull/179) that can be merged, with the same changes.

**Pull request closed without merging**
