### PR TITLE
Added change profile pic functionality

### PR DESCRIPTION
**Pull request by HarshHC**
Task: https://codein.withgoogle.com/dashboard/task-instances/6577602044100608/
Video: https://drive.google.com/file/d/1sTUPrCGmGw-T0JznC2vf0d_1vV0rK6ES/view

### CODE REVIEW

**Comment by Priya997** [comment]
Can you try to resolve the conflicts?

**Comment by Priya997** [comment]
@the-dagger This looks good to me and can be merged. 👍

**Comment by the-dagger** [comment]
@HarshHC Could you resolve the conflicts?

**Comment by HarshHC** [comment]
https://github.com/JBossOutreach/visiting-card-android/pull/178

**Pull request closed without merging**
