### PR TITLE
Added Geofence

### PR DESCRIPTION
**Pull request by crowded-geek**
Check by changing each `[ ]` to `[x]` Please take note of the white-space as it matters.

- This Pull request
   - [ ] Fixes a bug.
   - [x] Implements a new feature.
- [x] I have read the **[CONTRIBUTING.md]** .
- [x] I have included a description of changes below.
- [x] I have included screenshots  showing before and after the changes were made.
- [x] I have squashed the commits **(mandatory)**.

## Description / Changes

- Added Graphical geofence
- Fixes #<Issue no.>
- Link to [task](https://codein.withgoogle.com/dashboard/task-instances/4613383123894272/) 

## Screenshots

screenshot_20181124-010229

### CODE REVIEW

**Comment by the-dagger** [comment]
@crowded-geek Could you resolve the conflicts?

**Comment by crowded-geek** [comment]
@the-dagger Sure

**Comment by the-dagger** [comment]
Hi, any updates on this @crowded-geek? :)

**Comment by crowded-geek** [comment]
@the-dagger I had resolved the conflicts but due to new merges this PR is not usable anymore, just wait for a bit and I m creating a new PR give me like 10-15 mins.

**Comment by crowded-geek** [comment]
@the-dagger https://github.com/JBossOutreach/visiting-card-android/pull/204 this can be merged :D

**Comment by crowded-geek** [comment]
Closing this then :)

**Pull request merged**
