### PR TITLE
Added Custom maps pin

### PR DESCRIPTION
**Pull request by crowded-geek**
Check by changing each `[ ]` to `[x]` Please take note of the white-space as it matters.

- This Pull request
   - [x] Fixes a bug.
   - [x] Implements a new feature.
- [x] I have read the **[CONTRIBUTING.md]** .
- [x] I have included a description of changes below.
- [x] I have included screenshots  showing before and after the changes were made.
- [x] I have squashed the commits **(mandatory)**.

## Description / Changes

- Fixes [#81](https://github.com/JBossOutreach/visiting-card-android/issues/81)
- Link to [task](https://codein.withgoogle.com/dashboard/task-instances/5407780040081408/) 

## Screenshots

screenshot_20181101-195000

### CODE REVIEW

**Comment by the-dagger** [comment]
Could you take a look at the travis error?
Seems like a malformed Manifest file due to one of the earlier merges.

Post that, I'll be happy to merge this one :)

**Comment by crowded-geek** [comment]
Done 
@the-dagger Just saw the error

**Comment by crowded-geek** [comment]
@the-dagger The master's branch's build is failing because of a merge, that's why it's failing here too.

**Comment by the-dagger** [comment]
Ah alright.
I'll merge this, in case the build still fails, please send a private fixing it and mention me there

**Pull request merged**
